version: '3'

services:
  hivedb:
    image: mariadb
    container_name: hivedb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hive
    ports:
      - "3307:3306"
  hiveapp:
    build: .
    container_name: hiveapp
    working_dir: /app
    depends_on:
      - hivedb
    volumes:
      - ./hive-5-api:/app/
    links:
      - hivedb
    stdin_open: true
    tty: true
    ports:
      - "8001:8000"
      - "8181:8080"
